# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab18d7429311f06ebe59ba1ed9e361954bce4620a4994c2baba7b680b4af24a5c0a8ad0730025e57a130fff7411bb7dc400b2166f951ee41227bdff479576598

test:
  secret_key_base: 0529bf43809cbd0eac8017daecfe87c4b526d9347874911261ffd7cd0ad2cd7f8267800bd5fbf071abdb22e7d24f451038566e568529cf1598411498b4098e9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
